package it.polimi.deepse.dagsymb.launchers;/*
 * This file was automatically generated by EvoSuite
 * Wed May 16 13:25:00 GMT 2018
 */

import it.polimi.deepse.dagsymb.examples.PromoCalls;
import it.polimi.deepse.dagsymb.examples.UserCallDB;

public class Launcher4 {

  //Test case number: 0
  /*
   * 1 covered goal:
   * Goal 1. com.xspark.varyingdag.examples.calls.PromoCalls.run_driver(IJJI)V: path condition EvoSuiteWrapper_0_4 (id = 0)
   */

    public static void main(String[] args) {
	  int threshold = 2100;
      long minLocalLongCalls = 2100;
      long minAbroadLongCalls = 2100;
      int pastMonths = 1;
      int last24HLocalCallsLength = 3502;
      int last24HLocalCallsSize = 3502;
      int last24HAbroadCallsLength = 3502;
      int last24HAbroadCallsSize = 3502;
      int MonthCallsLength = 2990;
      int MonthCallsSize = 3000;
      int num_partitions = 500;
      PromoCalls promoCalls0 = new PromoCalls();
      boolean genData = false;
      String appName = "";
      if (args[12] != null && args[12].startsWith("-g")) genData = true;
      if (args[13] != null && !args[13].startsWith("-")) appName = args[12];
      //UserCallDB.addCallsToLast24HoursLocalCalls(3502, 3502);
      //UserCallDB.addCallsToLast24HoursAbroadCalls(3502, 3502);
      //promoCalls0.run(2100, 2100, 2100, 1);
      promoCalls0.run(threshold, minLocalLongCalls, minAbroadLongCalls, pastMonths, 
	  		  last24HLocalCallsLength, last24HLocalCallsSize, 
	  		  last24HAbroadCallsLength, last24HAbroadCallsSize, 
	  		  MonthCallsLength, MonthCallsSize, num_partitions, genData, appName);
  }
}
