package it.polimi.deepse.dagsymb.launchers;/*
 * This file was automatically generated by EvoSuite
 * Wed May 16 13:26:30 GMT 2018
 */

import it.polimi.deepse.dagsymb.examples.PromoCalls;
import it.polimi.deepse.dagsymb.examples.UserCallDB;

public class Launcher6 {

  //Test case number: 0
  /*
   * 1 covered goal:
   * Goal 1. com.xspark.varyingdag.examples.calls.PromoCalls.run_driver(IJJI)V: path condition EvoSuiteWrapper_0_6 (id = 0)
   */

    public static void main(String[] args) {
	  int threshold = 1006;
      long minLocalLongCalls = 1006;
      long minAbroadLongCalls = 1006;
      int pastMonths = 2;
      int last24HLocalCallsLength = 2003;
      int last24HLocalCallsSize = 2003;
      int last24HAbroadCallsLength = 1610;
      int last24HAbroadCallsSize = 1614;
      int MonthCallsLength = 2990;
      int MonthCallsSize = 3000;
      int num_partitions = 500;
      PromoCalls promoCalls0 = new PromoCalls();
      boolean genData = false;
      String appName = "";
      if (args[12] != null && args[12].startsWith("-g")) genData = true;
      if (args[13] != null && !args[13].startsWith("-")) appName = args[12];
      //UserCallDB.addCallsToLast24HoursAbroadCalls(2003, 2003);
      //UserCallDB.addCallsToLast24HoursLocalCalls(1610, 1614);
      //promoCalls0.run(1006, 1006, 1006, 2);
      promoCalls0.run(threshold, minLocalLongCalls, minAbroadLongCalls, pastMonths, 
	  		  last24HLocalCallsLength, last24HLocalCallsSize, 
	  		  last24HAbroadCallsLength, last24HAbroadCallsSize, 
	  		  MonthCallsLength, MonthCallsSize, num_partitions, genData, appName);
  }
}
