package it.polimi.deepse.dagsymb.launchers;/*
 * This file was automatically generated by EvoSuite
 * Wed May 16 13:15:37 GMT 2018
 */

import it.polimi.deepse.dagsymb.examples.PromoCalls;

public class Launcher1 {

  //Test case number: 0
  /*
   * 1 covered goal:
   * Goal 1. com.xspark.varyingdag.examples.calls.PromoCalls.run_driver(IJJI)V: path condition EvoSuiteWrapper_0_1 (id = 0)
   */

    public static void main(String[] args) {
    	int threshold = 1994;
        long minLocalLongCalls = 1994;
        long minAbroadLongCalls = 1994;
        int pastMonths = 0;
        int last24HLocalCallsLength = 3361;
        int last24HLocalCallsSize = 1397;
        int last24HAbroadCallsLength = 3361;
        int last24HAbroadCallsSize = 1397;
        int MonthCallsLength = 2990;
        int MonthCallsSize = 3000;
        PromoCalls promoCalls0 = new PromoCalls();
        //promoCalls0.run(1994, 1994, 1994, 0);
        promoCalls0.run(threshold, minLocalLongCalls, minAbroadLongCalls, pastMonths, 
		  		  last24HLocalCallsLength, last24HLocalCallsSize, 
		  		  last24HAbroadCallsLength, last24HAbroadCallsSize, 
		  		  MonthCallsLength, MonthCallsSize);
        
  }
}
