package it.polimi.deepse.dagsymb.launchers;/*
 * This file was automatically generated by EvoSuite
 * Wed May 16 13:21:27 GMT 2018
 */

import it.polimi.deepse.dagsymb.examples.PromoCalls;
import it.polimi.deepse.dagsymb.examples.UserCallDB;

public class Launcher {

  //Test case number: 0
  /*
   * 1 covered goal:
   * Goal 1. com.xspark.varyingdag.examples.calls.PromoCalls.run_driver(IJJI)V: path condition EvoSuiteWrapper_0_2 (id = 0)
   */

    public static void main(String[] args) {
      PromoCalls promoCalls0 = new PromoCalls(); //args[10] is the IGuardEvaluator implementation FQ Classname
      UserCallDB.addCallsToLast24HoursLocalCalls(Integer.parseInt(args[4]), Integer.parseInt(args[5]));
      UserCallDB.addCallsToLast24HoursAbroadCalls(Integer.parseInt(args[6]), Integer.parseInt(args[7]));
      UserCallDB.addCallsToMonthCalls(Integer.parseInt(args[8]), Integer.parseInt(args[9]));
      promoCalls0.run(Integer.parseInt(args[0]), Integer.parseInt(args[1]), Integer.parseInt(args[2]), Integer.parseInt(args[3]));
  }
}
