package it.polimi.deepse.dagsymb.launchers;/*
 * This file was automatically generated by EvoSuite
 * Wed May 16 13:18:58 GMT 2018
 */

import it.polimi.deepse.dagsymb.examples.PromoCalls;
import it.polimi.deepse.dagsymb.examples.UserCallDB;

public class Launcher3 {

  //Test case number: 0
  /*
   * 1 covered goal:
   * Goal 1. com.xspark.varyingdag.examples.calls.PromoCalls.run_driver(IJJI)V: path condition EvoSuiteWrapper_0_3 (id = 0)
   */

    public static void main(String[] args) {
	  int threshold = 1811;
      long minLocalLongCalls = 1707;
      long minAbroadLongCalls = 3102L;
      int pastMonths = 0;
      int last24HLocalCallsLength = 2251;
      int last24HLocalCallsSize = 2251;
      int last24HAbroadCallsLength = 2635;
      int last24HAbroadCallsSize = 2635;
      int MonthCallsLength = 2990;
      int MonthCallsSize = 3000;
      PromoCalls promoCalls0 = new PromoCalls();
      //UserCallDB.addCallsToLast24HoursLocalCalls(2251, 2251);
      //promoCalls0.run(1811, 1707, 3102L, 0);
      promoCalls0.run(threshold, minLocalLongCalls, minAbroadLongCalls, pastMonths, 
	  		  last24HLocalCallsLength, last24HLocalCallsSize, 
	  		  last24HAbroadCallsLength, last24HAbroadCallsSize, 
	  		  MonthCallsLength, MonthCallsSize);
  }
}
