package it.polimi.deepse.dagsymb.launchers;/*
 * This file was automatically generated by EvoSuite
 * Wed May 16 13:15:37 GMT 2018
 */

import it.polimi.deepse.dagsymb.examples.PromoCalls;

public class Launcher1 {

  //Test case number: 0
  /*
   * 1 covered goal:
   * Goal 1. com.xspark.varyingdag.examples.calls.PromoCalls.run_driver(IJJI)V: path condition EvoSuiteWrapper_0_1 (id = 0)
   */

    public static void main(String[] args) {
      PromoCalls promoCalls0 = new PromoCalls();
      promoCalls0.run(1994, 1994, 1994, 0);
  }
}
