/*
 * This file was automatically generated by EvoSuite
 * Wed May 16 13:21:27 GMT 2018
 */

import it.polimi.deepse.dagsymb.examples.UserCallDB;
import org.junit.Test;
import it.polimi.deepse.dagsymb.examples.PromoCalls;

public class PromoCalls_run_driver_PC_0_2_Test {

  //Test case number: 0
  /*
   * 1 covered goal:
   * Goal 1. com.xspark.varyingdag.examples.calls.PromoCalls.run_driver(IJJI)V: path condition EvoSuiteWrapper_0_2 (id = 0)
   */

  @Test(timeout = 4000)
  public void test0() {
      PromoCalls promoCalls0 = new PromoCalls();
      promoCalls0.addToDatasetLast24HoursLocalCalls(2635, 2635);
      promoCalls0.addToDatasetLast24HoursAbroadCalls(2635, 2635);
      promoCalls0.run(2600, 2600, 2600, 0);
  }
}
