/*
 * This file was automatically generated by EvoSuite
 * Wed May 16 13:15:37 GMT 2018
 */

import org.junit.Test;
import it.polimi.deepse.dagsymb.examples.PromoCalls;
import org.junit.runner.RunWith;
import shaded.org.evosuite.runtime.EvoRunner;

@RunWith(EvoRunner.class) @shaded.org.evosuite.runtime.EvoRunnerParameters(mockJVMNonDeterminism = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class PromoCalls_run_driver_PC_0_1_Test extends PromoCalls_run_driver_PC_0_1_Test_scaffolding {

  //Test case number: 0
  /*
   * 1 covered goal:
   * Goal 1. com.xspark.varyingdag.examples.calls.PromoCalls.run_driver(IJJI)V: path condition EvoSuiteWrapper_0_1 (id = 0)
   */

  @Test(timeout = 4000)
  public void test0() {
      PromoCalls promoCalls0 = new PromoCalls();
      promoCalls0.run(1994, 1994, 1994, 0);
  }
}
