/*
 * This file was automatically generated by EvoSuite
 * Wed May 16 13:15:37 GMT 2018
 */

import org.junit.Test;
import it.polimi.deepse.dagsymb.examples.PromoCalls;

public class PromoCalls_run_driver_PC_0_1_Test {

  //Test case number: 0
  /*
   * 1 covered goal:
   * Goal 1. com.xspark.varyingdag.examples.calls.PromoCalls.run_driver(IJJI)V: path condition EvoSuiteWrapper_0_1 (id = 0)
   */

  @Test(timeout = 4000)
  public void test0() {
      PromoCalls promoCalls0 = new PromoCalls();
      promoCalls0.run(1994, 1994, 1994, 0);
  }
}
