/*
 * This file was automatically generated by EvoSuite
 * Wed May 16 13:26:30 GMT 2018
 */

import it.polimi.deepse.dagsymb.examples.UserCallDB;
import org.junit.Test;
import it.polimi.deepse.dagsymb.examples.PromoCalls;
import org.junit.runner.RunWith;
import shaded.org.evosuite.runtime.EvoRunner;
import shaded.org.evosuite.runtime.EvoRunnerParameters;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class PromoCalls_run_driver_PC_0_6_Test extends PromoCalls_run_driver_PC_0_6_Test_scaffolding {

  //Test case number: 0
  /*
   * 1 covered goal:
   * Goal 1. com.xspark.varyingdag.examples.calls.PromoCalls.run_driver(IJJI)V: path condition EvoSuiteWrapper_0_6 (id = 0)
   */

  @Test(timeout = 4000)
  public void test0() {
      PromoCalls promoCalls0 = new PromoCalls();
      UserCallDB.addCallsToLast24HoursAbroadCalls(2003, 2003);
      UserCallDB.addCallsToLast24HoursLocalCalls(1610, 1614);
      promoCalls0.run(1006, 1006, 1006, 2);
  }
}
